source(file = "Main/functions.R")
source(file = "Main/libraries.R")
source(file = "Main/global_vars.R")
source(file = "Main/03_open_expression_tables.R")
source(file = "Main/04_remove_gene_id_version.R")
source(file = "Main/05_merge.R")
source(file = "Main/09_process_l_pc.R")

# Select the longest transcripts for the data frames with the epressed genes (the df_sym_ec1 data frames
# This script create l_Expressed_Genes, which is the "complete?" final master list of expressed genes for each dataset

glimpse(summary_stats$ENCFF227HKF.tsv$df_sym_ec1)

select_largest_transcripts <- function(list_of_filtered_stats) {
  #
  #takes a summary_stats list generated by 09,takes the df_sym_ec1 protein coding table, and returns a data frame where the Genes that remain have the longest transcript length
  #If there are transcipt length that are the same, then this output must be run through remove_duplicate_symbols
  #
  #
  expressed_genes <- list_of_filtered_stats$df_sym_ec1
  expressed_genes <- expressed_genes %>%
    ungroup() %>%
    mutate("len_Transcript_ID" = expressed_genes$End - expressed_genes$Start)%>%
    group_by(Symbol)%>%
    slice_max(order_by = len_Transcript_ID, n=1)%>%
    ungroup()
  return (expressed_genes)
}

remove_duplicate_symbols <- function(expressed_genes_df) {
  #
  #takes the dataframe output by select_largest_transcripts, and removes duplicate Symbols. The first one of the duplicate it encounters is selected
  #
  expressed_genes_df <- expressed_genes_df %>%
    distinct(Symbol, .keep_all= TRUE)
  return (expressed_genes_df)
}

with_largest_transcripts <- lapply(summary_stats, select_largest_transcripts)

l_Expressed_Genes<- lapply(with_largest_transcripts,remove_duplicate_symbols)


#---------Getting the number of duplicates (same transcript lengths) for each table
get_n_duplicate_symbols <- function(expressed_genes_df) { 
  dup_bool <- duplicated(x = expressed_genes_df$Symbol)
  symbols <- as.list(expressed_genes_df$Symbol)
  dup_symbols <- symbols[dup_bool]
  n_duplicates <- length(dup_symbols)
  return (n_duplicates)
}

#--------Check to make sure the duplicte removal was a total success.
stopifnot(nrow(l_Expressed_Genes$ENCFF227HKF.tsv) - get_n_duplicate_symbols(l_Expressed_Genes$ENCFF227HKF.tsv) == nrow(l_Expressed_Genes$ENCFF227HKF.tsv))




#---------There is an issue here where the num rows of our data frames are not equal to the number of symbols/group size. I will investigate why

#----------------Check to guarentee they pick the propper one

# genes <- summary_stats$ENCFF227HKF.tsv$df_sym_ec1
# # -- load
# 
# #--try and slice by largest transcript length
# 
# max_len_genes <- genes %>%
#   mutate("len_Transcript_ID" = genes$End - genes$Start) %>%
#   group_by(Symbol) %>%
#   slice_max(order_by = len_Transcript_ID, n=1)%>%
#   ungroup()
# glimpse(max_len_genes)
# 
# #-------get the smybols that are duplicated in our sliced gene list
# 
# dup_bool <- duplicated(x = max_len_genes$Symbol)
# symbols <- as.list(max_len_genes$Symbol)
# dup_symbols <- symbols[dup_bool]
# 
# #-------filter for a signle duplicated symbol in max_len_genes
# "Zzef1" %in% max_len_genes$Symbol
# 
# duplicated_max_len_genes <- max_len_genes%>%
#   filter(max_len_genes$Symbol %in% dup_symbols)

#------ In conclusion. The reason for why our origonal slice_max data frame is NOT rowlength == group size, is due to the fact that some symbols have len_transcript_ID that are IDENTICAL
#------ To get over this, I'll just arbitrarily select one of the transcripts when the lengths are identical



# 
# %>%
#   group_by(Symbol)%>%
#   top_n(n=1)
#   
  